baseURL: 'https://yun-20459.github.io'
languageCode: zh-tw
title: 隨寫日誌
theme: cactus

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about"
      weight: 2
    - name: "Posts"
      url: "/posts"
      weight: 3
    - name: "Resources"
      url: "/resources"
      weight: 4
    - name: "Search"
      url: "/search"
      weight: 5
    - name: "Tags"
      url: "/tags"
      weight: 6

markup:
  goldmark:
    renderer:
      hardWraps: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

pygmentsStyle: "pygments"
pygmentsUseClasses: true

params:
  colortheme: dark
  mathjax: true
  showAllPostsOnHomePage: false
  showAllPostsArchive: false
  tagsOverview: false
  postsOnHomePage: 10
  show_updated: true
  showReadTime: true
  social:
    - name: "github"
      link: "https://github.com/yun-20459"
    - name: "linkedin"
      link: "https://www.linkedin.com/in/erinli0405"
    - name: "email"
      link: "b08502041@csie.ntu.edu.tw"
  css:
    - "css/highlight.css"
    - "css/style-dark.css"
    - "css/search.css"

copyright: "Erin Li"

permalinks:
  - posts: ":year/:month/:day/:filename/"

outputs:
  home:
    - HTML
    - RSS
    - JSON


